
version: '3.8'

# Define your services
services:
  # Your server service
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3009:3009
    depends_on:
      - db

  # MySQL database service
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password@123
      MYSQL_DATABASE: production
      MYSQL_USER: ishimwe
      MYSQL_PASSWORD: Password@123
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
 
  # Sequelize CLI service
  sequelize-cli:
   build:
    context: .
   environment:
    NODE_ENV: production
   command: npx sequelize-cli db:migrate
   depends_on:
    - db
   working_dir: /usr/src/app
   volumes:
    - .:/usr/src/app
# Define volumes
volumes:
  db-data:
